# Default values for my-fastapi-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: john19968010/fastapi-template
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 10009
  name: fastapi-template-svc
  type: NodePort

volumes: 
- name: log
  emptyDir:
    sizeLimit: 500Mi

volumeMounts: 
- name: log
  mountPath: "/usr/src/app/log"
  readOnly: true